log:
  level: INFO

entryPoints:
  web:
    # http
    address: ":80"
    # http:
    #   # https://docs.traefik.io/routing/entrypoints/#entrypoint
    #   redirections:
    #     entryPoint:
    #       to: web-secure

  # web-secure:
  #   # https
  #   address: ':443'

# certificatesResolvers:
#   letsencrypt:
#     # https://docs.traefik.io/master/https/acme/#lets-encrypt
#     acme:
#       email: 'h.vahatra.d@gmail.com'
#       storage: /etc/traefik/acme/acme.json
#       # https://docs.traefik.io/master/https/acme/#httpchallenge
#       httpChallenge:
#         entryPoint: web

http:
  routers:
    web-secure-router:
      rule: "Host(`myapp.localhost`)"
      entryPoints:
        - web
        # - web-secure
      service: django
      # tls:
      #   # https://docs.traefik.io/master/routing/routers/#certresolver
      #   certResolver: letsencrypt

    # web-media-router:
    #   rule: "(Host(`myapp.localhost`) && PathPrefix(`/media/`))"
    #   entryPoints:
    #     - web-secure
    #   service: django-media
    #   tls:
    #     certResolver: letsencrypt

  # middlewares:
  #   csrf:
  #     # https://docs.traefik.io/master/middlewares/headers/#hostsproxyheaders
  #     # https://docs.djangoproject.com/en/dev/ref/csrf/#ajax
  #     headers:
  #       hostsProxyHeaders: ['X-CSRFToken']

  services:
    django:
      loadBalancer:
        servers:
          - url: http://django:5000

    # django-media:
    #   loadBalancer:
    #     servers:
    #       - url: http://nginx:80

providers:
  # https://docs.traefik.io/master/providers/file/
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
